name: Run linters

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  golangci-lint:
    name: Lint the project using GolangCI Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
      - name: Run GolangCI-Lint
        uses: ./
        with:
          config: .golangci.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
